# use base image
FROM ubuntu:18.04

# define maintainer
# MAINTAINER niu (niu@docker.com)
LABEL maintainer="niu@docker.com"

# install ca
RUN apt-get update -y && \
    apt-get install apt-transport-https ca-certificates -y


# add apt source
ADD sources.list /etc/apt/sources.list


# install nginx, run nginx with no daemon
RUN apt-get update -y && \
    rm -rf /var/lib/apt/lists/*
    # apt-get install -y nginx && \
    # rm -rf /var/lib/apt/lists/* && \
    # echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
    # chown -R www-data:www-data /var/lib/nginx

RUN echo "Asia/Shanghai" > /etc/timezone

# add script
# ADD run.sh /run.sh
# RUN chmod 755 /*.sh

# volume
# VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx"]

# work dir
# WORKDIR /etc/nginx

# cmd
# CMD ["/run.sh"]

# EXPOSE 80
# EXPOSE 443